cache:
  directories:
    - node_modules

env:
  global:
    - ANDROID_HOME=/usr/local/android-sdk
    - ANDROID_SDK_ROOT=/usr/local/android-sdk
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
    - export QEMU_AUDIO_DRV=none

jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - "10"

      before_install:
        - npm install -g yarn
      script:
        - yarn ci

    - stage: build
      name: "Build Android"
      language: android
      android:
        components:
          - tools
        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      before_install:
        - echo 'count=0' > /home/travis/.android/repositories.cfg # Avoid harmless sdkmanager warning
        - yes | sdkmanager "platform-tools" >/dev/null
        - yes | sdkmanager "tools" >/dev/null # A second time per Travis docs, gets latest versions
        - yes | sdkmanager "build-tools;28.0.3" >/dev/null # Implicit gradle dependency - gradle drives changes
        - yes | sdkmanager "platforms;android-28" >/dev/null # We need the API of the current compileSdkVersion from gradle.properties
        - yes | sdkmanager "extras;android;m2repository" >/dev/null
        - nvm install 10
        - node --version
        - npm install -g yarn
        - yarn -version
        - yarn
      script:
        - yarn detox build -c android.emu.release

    - stage: build
      name: "Build iOS"
      language: objective-c
      os: osx
      osx_image: xcode10.1
      before_install:
        - nvm install 10
        - node --version
        - npm install -g yarn
        - yarn -version
        - yarn
        - softwareupdate --list
        - softwareupdate --install "Command Line Tools (macOS High Sierra version 10.13) for Xcode-10.1"
        - brew tap wix/brew
        - brew install applesimutils
        - yarn global add react-native-cli
        - yarn detox clean-framework-cache &&  yarn detox build-framework-cache
        - xcrun simctl boot "iPhone 5s" || true
        - react-native start &
      script:
        - yarn detox build -c ios.sim.debug
        - yarn detox test -c ios.sim.debug -l verbose

deploy:
  provider: npm
  email: guhungry@gmail.com
  api_key:
    secure: KLmoUMac1wc5/2no4fIqUDarl4ET6gaJ8BNSYDXLMhFriCLtR7DzIqsLHPLL4HXbNySBs7RPCoJIOlPA2e/6HYjwWi/Ah+r6sEESuq2bETrw0yUa8O210TYy8GVPNkZkY8ZGCW94CcH+VMPuOqCqKMFiLVIsSIaUqEUYPRreb94yIv1B14sgs+s4GYG+RlwIKn62LxTxY/O3AMGFefLQsszhoVHfZf7XZUbKhQXSD/6KF9qABmgLSKMn4OdDgQdpRAU2KeLtnTXCvcgw9gZwP0AqTWEflM9oRHOxfWUIRb3uoaU+8zCdAZ+eODUpuJRDWzyXBa+DyGAlVEnFroV5dCnT020zfrF7nBB5Fse9inT8wiQ+oI0kmswEg+kqXCY6DFlSeA5RuEMkT3Ix4w9TGqByOaBb97uPJSxPeK9eUBLa6tJgdSee2pfce+fXDOgQybjhuAUsrvBswQBff6yiIn1jDiK5flPDzC4dD6OZCRGglPbLLdooJIS22rrCu1pqutnNIWS0ud50LA0WMMruicfX+djOyhBAN4wt3YEpUh4cdAGIuMdvdBFQLnNXQ/VhqD40A6Z2yFpclK6it2YQmMmCShtaT8ehvTzgy5v03NwMG79A/KXcMQGUSl5ztglbxlAZoSNCm9fJCbvNIn+V8TnB3dVBWdDMvdzLGLYqyy0=
#  on:
#    tags: true
#    branch: master